### ISSUE TITLE
PrestoConnectionManager error on 0.14

### ISSUE THREAD

**Issue by rmgpinto** [fishtown-analytics/dbt-presto#6]
Hi,

After upgrading to 0.14, I'm getting this error:
```
sh-4.2$ dbt debug
Running with dbt=0.14.0
dbt version: 0.14.0
python version: 3.7.3
python path: /usr/bin/python3
os info: Linux-4.9.125-linuxkit-x86_64-with-glibc2.2.5
Using profiles.yml file at /home/dbt/.dbt/profiles.yml

Configuration:
  profiles.yml file [OK found and valid]
  dbt_project.yml file [OK found and valid]
  profile: default [OK found]
  target: data_lake [OK found]

Required dependencies:
 - git [OK found]

Connection:
  host: presto_server.cluster.svc.local
  port: 8080
  database: data_lake
  Connection test: ERROR

dbt was unable to connect to the specified database.
The database returned the following error:

  >'PrestoConnectionManager' object has no attribute 'get'

Check your database credentials and try again. For more information, visit:
https://docs.getdbt.com/docs/configure-your-profile
```
Do you have any tips on how to debug this issue?

Thanks

**Comment by drewbanin** [comment]
Hey @rmgpinto! I believe we'll need to update this package to be compatible with v0.14.0. In its current state, it's only compatible with dbt v0.13.1 (actually `0.13.1-rc1`!)

I can have a look at what's involved in upgrading this package to work with dbt-core v0.14.0. Separately, I'll have a think about how we can better keep this package (and `dbt-spark`) up-to-date with dbt-core. They very well might lag behind the releases of redshift/snowflake/bigquery, but we need to have some sort of process in place for keeping these plugins current!

Curious if you have any thoughts!

**Comment by rmgpinto** [comment]
I'd love to help but I'd need to submerge myself in dbt codebase. I'm afraid I don't have a lot of time for that.
Do you think the changes are easy to make?

**Comment by drewbanin** [comment]
I think the changes are going to be pretty minor in nature, but I'd also need to spend some time compiling the list of changes that need to be made. Let me see if I can carve out some time in the next day or two to investigate!

**Comment by rmgpinto** [comment]
Thanks, if they're minor I'd be able to do them.

**Comment by drewbanin** [comment]
Hey @rmgpinto - the big difference between 0.13.x and 0.14.0 is that each thread now manages its own connection to the database. You can check out the required changes here: https://github.com/fishtown-analytics/dbt-presto/pull/7

Hope you don't mind that I whipped this together... I wasn't really sure exactly what needed to change before I dug way into it! I mostly did this by comparing the presto method overrides to the ["base" implementation](https://github.com/fishtown-analytics/dbt/blob/dev/0.14.1/core/dbt/adapters/sql/connections.py). I just needed to tweak some method signatures to get everything working.

I ran this the code in #7 locally and created a couple of dummy views/tables. If you're able to give it a spin, I'd feel a lot more confident merging that PR! Let me know in the PR if you have any issues :)

**Comment by drewbanin** [comment]
fixed in https://github.com/fishtown-analytics/dbt-presto/pull/7
